zuul:
  routes:
    hello:
      path: /hello/**
      serviceId: hello-service
    feign:
      path: /consumer/**
      serviceId: ribbon-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 8889
spring:
  application:
    name: api-gateway
demo:
  filter:
    root: zuul-gateway/src/main/java/com/hearing/zuulgateway/filter
    interval: 5