spring:
  application:
    name: eureka-server

server:
  port: 1111

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:1112/eureka/
  server:
    enable-self-preservation: false